const API=localStorage.getItem("CELULAR_STAR_API")||"https://desktop-tl72une.tail367c47.ts.net/celularstar";let inventory=[],allInventory=[],user=null;const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const token=()=>sessionStorage.getItem("cs_token");
async function api(path,opt={}){opt.headers={...(opt.headers||{}),Authorization:`Bearer ${token()}`};let r=await fetch(API+path,opt);if(r.status===401){sessionStorage.removeItem("cs_token");showLogin();throw Error("auth")}return r}
function showLogin(){$("#loginView").style.display="block";$("#panelView").style.display="none"}function showPanel(){$("#loginView").style.display="none";$("#panelView").style.display="block"}
function mapRows(rows){return rows.map(x=>({id:x.codigo+"|"+x.codigo_almacen,codigo:x.codigo,almacen:String(x.codigo_almacen),sucursal:x.sucursal,model:x.modelo,sql:x.stock_sql,physical:x.stock_validado??x.stock_sql,validated:x.validacion_vigente}))}
async function load(){let r=await api("/api/inventario-supervisor"),j=await r.json();user=j.usuario;allInventory=mapRows(j.inventario||[]);$(".welcome p").innerHTML=`Hola, <b>${user.nombre}</b>. Revisa y confirma la existencia física disponible.`;
 if(user.rol==="ADMIN"){setupAdmin();}else{inventory=allInventory;$("#adminBranchBar").style.display="none";$(".welcome h1").textContent=allInventory[0]?.sucursal||"Tu sucursal";render()}}
function setupAdmin(){let sel=$("#adminBranch"),seen=new Map();allInventory.forEach(x=>seen.set(x.almacen,x.sucursal));sel.innerHTML='<option value="ALL">Todas las sucursales</option>'+[...seen.entries()].sort((a,b)=>a[1].localeCompare(b[1])).map(([c,n])=>`<option value="${c}">${n} · ${c}</option>`).join("");$("#adminBranchBar").style.display="flex";$(".welcome h1").textContent="Administración";sel.onchange=()=>{let v=sel.value;inventory=v==="ALL"?allInventory:allInventory.filter(x=>x.almacen===v);$(".welcome h1").textContent=v==="ALL"?"Todas las sucursales":seen.get(v);render()};inventory=allInventory;render()}
function totals(){let a=inventory.reduce((s,x)=>s+x.sql,0),b=inventory.reduce((s,x)=>s+x.physical,0),d=b-a;$("#modelCount").textContent=inventory.length;$("#sqlTotal").textContent=a;$("#physicalTotal").textContent=b;$("#mobileTotal").textContent=b;$("#diffTotal").textContent=(d>0?"+":"")+d}
function render(){let q=$("#productSearch").value.toLowerCase(),l=inventory.filter(x=>x.model.toLowerCase().includes(q));$("#visibleCount").textContent=l.length+" modelos";$("#inventoryList").innerHTML=l.map(x=>{let d=x.physical-x.sql;return `<article class="inventory-item"><div class="product-name"><small>${x.validated?"VALIDADO":"PENDIENTE"}${user?.rol==="ADMIN"?" · "+x.sucursal:""}</small><h3>${x.model}</h3></div><div class="sql-stock"><span>Sistema / SQL</span><b>${x.sql}</b></div><div class="physical"><span>Disponibilidad física</span><div class="physical-control"><button class="minus" data-id="${x.id}">−</button><input value="${x.physical}" readonly><button class="plus" data-id="${x.id}">+</button></div></div><div class="difference"><span>Diferencia</span><b class="${d>0?"plus":d<0?"minus":""}">${d>0?"+":""}${d}</b></div><div class="item-actions"><button class="confirm ${x.validated?"validated":""}" data-id="${x.id}">${x.validated?"✓ Validado":"Confirmar "+x.physical}</button></div></article>`}).join("");$$(".plus").forEach(b=>b.onclick=()=>chg(b.dataset.id,1));$$(".minus").forEach(b=>b.onclick=()=>chg(b.dataset.id,-1));$$(".confirm").forEach(b=>b.onclick=()=>save(b.dataset.id));totals()}
function find(id){return allInventory.find(i=>i.id===id)}function chg(id,n){let x=find(id);x.physical=Math.max(0,x.physical+n);x.validated=false;render()}
async function save(id,quiet=false){let x=find(id);let r=await api("/api/validar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({codigo:x.codigo,codigo_almacen:x.almacen,stock_validado:x.physical})});if(r.ok){x.validated=true;render();if(!quiet)Swal.fire({toast:true,position:"top-end",icon:"success",title:"Existencia validada",showConfirmButton:false,timer:1300})}}
async function validateAll(){for(const x of inventory)await save(x.id,true);Swal.fire({title:"Inventario validado",icon:"success",confirmButtonColor:"#07111f"})}
$("#loginForm").onsubmit=async e=>{e.preventDefault();let r=await fetch(API+"/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({usuario:$("#user").value,password:$("#pass").value})});let j=await r.json();if(!r.ok)return Swal.fire({title:"Acceso denegado",text:j.error||"Credenciales incorrectas",icon:"error"});sessionStorage.setItem("cs_token",j.token);showPanel();load()};
$("#showPass").onclick=()=>{$("#pass").type=$("#pass").type==="password"?"text":"password"};$("#logout").onclick=async()=>{try{await api("/api/logout",{method:"POST"})}catch(e){}sessionStorage.removeItem("cs_token");location.reload()};$("#productSearch").oninput=render;$("#validateAll").onclick=validateAll;$("#mobileValidate").onclick=validateAll;(async()=>{if(token()){try{showPanel();await load()}catch(e){showLogin()}}else showLogin()})();